name: Build FAST build docker image

on:
  push:
  workflow_dispatch:
    inputs:
      deploy:
        description: Deploy to packages
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set variables
        run: |
          FAST_VERSION=$(python3 get_latest_fast_version.py)
          echo "FAST_VERSION=$FAST_VERSION" >> "$GITHUB_ENV"

      - name: Build
        run: |
          docker build . -f build.Dockerfile -t fast:${FAST_VERSION}-build

      - name: Save docker image to file
        run: |
          docker save -o fast-${FAST_VERSION}-build.tar fast:${FAST_VERSION}-build

      - name: Upload docker image file as artifact
        uses: actions/upload-artifact@v4
        with:
          path: fast-*.tar
          if-no-files-found: error

      - name: Test image
        run: |
          docker run --rm fast:${FAST_VERSION}-build

      - name: Login to GitHub Container Registry
        if: ${{ inputs.deploy }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container
        if: ${{ inputs.deploy }}
        run: |
          docker push fast:${FAST_VERSION}-build
